<?php
namespace SclZfCartSagepay\Data;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-15 at 17:30:37.
 */
class DataProviderTest extends \PHPUnit_Framework_TestCase
{
    private $config;
    
    /**
     * @var DataProvider
     */
    protected $object;

    private function setUpObject(array $config)
    {
        $this->object = new DataProvider($config);
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $config = include __DIR__ . '/../../../../config/module.config.php';
        $this->config = $config['scl_zf_cart_sagepay'];

        $this->setUpObject($this->config);
    }

    /**
     * @covers SclZfCartSagepay\Data\DataProvider::getVersion
     */
    public function testGetVersion()
    {
        $this->assertEquals($this->config['version'], $this->object->version);
    }

    /**
     * @covers SclZfCartSagepay\Data\DataProvider::getAccount
     */
    public function testGetAccount()
    {
        $this->assertEquals($this->config['vsp_account'], $this->object->account);
    }

    /**
     * @covers SclZfCartSagepay\Data\DataProvider::getUrl
     */
    public function testGetUrl()
    {
        $this->assertEquals($this->config['connection']['test']['url'], $this->object->url);
    }
}
