<?php
namespace SclZfCartSagepayTests\Data;

use SclZfCartSagepay\Data\Config;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-15 at 17:30:37.
 */
class ConfigTest extends \PHPUnit_Framework_TestCase
{
    private $config;

    /**
     * @var Config
     */
    protected $object;

    private function setUpObject(array $config)
    {
        $this->object = new Config($config);
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $config = include __DIR__ . '/../../../config/module.config.php';
        $this->config = $config['scl_zf_cart_sagepay'];

        $this->setUpObject($this->config);
    }

    /**
     * @covers SclZfCartSagepay\Data\Config::__get
     */
    public function testReadProperties()
    {
        $this->assertEquals($this->config['version'], $this->object->version);

        $this->assertEquals($this->config['vsp_account'], $this->object->account);

        $this->assertEquals($this->config['connection']['test']['url'], $this->object->url);
    }
}
