<?php
namespace SclZfCartSagepayTests\Data;

use SclZfCartSagepay\Data\CryptData;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-15 at 17:30:38.
 */
class CryptDataTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CryptData
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CryptData;
    }

    /**
     * @covers SclZfCartSagepay\Data\CryptData::add
     * @covers SclZfCartSagepay\Data\CryptData::__toString
     * @todo   Test encoding
     */
    public function testAdd()
    {
        $this->object->add('field1', 'value1')
            ->add('field2', 'value2');

        $this->assertEquals('field1=value1&field2=value2', (string) $this->object);
    }
}
