<?php
namespace SclZfCartSagepayTests\Service;

use SclZfCartSagepay\Service\SagepayFactory;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-15 at 17:30:38.
 */
class SagepayFactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var SagepayFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SagepayFactory;
    }

    /**
     * @covers SclZfCartSagepay\Service\SagepayFactory::createService
     */
    public function testCreateService()
    {
        $serviceLocator = $this->getMock('Zend\ServiceManager\ServiceLocatorInterface');

        $options = $this->getMockBuilder('SclZfCartSagepay\Options\SagepayOptions')
            ->disableOriginalConstructor()
            ->getMock();

        $serviceLocator->expects($this->at(0))
            ->method('get')
            ->with($this->equalTo('SclZfCartSagepay\Options\SagepayOptions'))
            ->will($this->returnValue($options));

        $blockCipher = $this->getMockBuilder('Zend\Crypt\BlockCipher')
            ->disableOriginalConstructor()
            ->getMock();

        $serviceLocator->expects($this->at(1))
            ->method('get')
            ->with($this->equalTo('SclZfCartSagepay\BlockCipher'))
            ->will($this->returnValue($blockCipher));

        $cryptData = $this->getMock('SclZfCartSagepay\Data\CryptData');

        $serviceLocator->expects($this->at(2))
            ->method('get')
            ->with($this->equalTo('SclZfCartSagepay\Data\CryptData'))
            ->will($this->returnValue($cryptData));

        $connOptions = $this->getMock('SclZfCartSagepay\Options\ConnectionOptions');

        $options->expects($this->any())
                ->method('getConnectionOptions')
                ->will($this->returnValue($connOptions));

        $sagepay = $this->object->createService($serviceLocator);

        $this->assertInstanceOf('SclZfCartSagepay\Sagepay', $sagepay);
    }
}
