<?php
namespace SclZfCartSagepay\Service;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-15 at 17:30:38.
 */
class BlockCipherFactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var BlockCipherFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new BlockCipherFactory;
    }

    /**
     * @covers SclZfCartSagepay\Service\BlockCipherFactory::createService
     * @todo   Implement testCreateService().
     */
    public function testCreateService()
    {
        $serviceLocator = $this->getMock('Zend\ServiceManager\ServiceLocatorInterface');

        $cipher = $this->object->createService($serviceLocator);

        $this->assertInstanceOf('Zend\Crypt\BlockCipher', $cipher);
    }
}
