<?php
namespace SclZfCartSagepay\Service;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-15 at 17:30:38.
 */
class DataProviderFactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DataProviderFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DataProviderFactory;
    }

    /**
     * @covers SclZfCartSagepay\Service\DataProviderFactory::createService
     * @todo   Implement testCreateService().
     */
    public function testCreateService()
    {
        $config = include __DIR__ . '/../../../../config/module.config.php';

        $serviceLocator = $this->getMock('Zend\ServiceManager\ServiceLocatorInterface');

        $serviceLocator->expects($this->at(0))
            ->method('get')
            ->with($this->equalTo('Config'))
            ->will($this->returnValue($config));

        $blockCipher = $this->getMockBuilder('Zend\Crypt\BlockCipher')
            ->disableOriginalConstructor()
            ->getMock();

        $serviceLocator->expects($this->at(1))
            ->method('get')
            ->with($this->equalTo('SclZfCartSagepay\BlockCipher'))
            ->will($this->returnValue($blockCipher));

        $cryptData = $this->getMock('SclZfCartSagepay\Data\CryptData');

        $serviceLocator->expects($this->at(2))
            ->method('get')
            ->with($this->equalTo('SclZfCartSagepay\Data\CryptData'))
            ->will($this->returnValue($cryptData));

        $cipher = $this->object->createService($serviceLocator);

        $this->assertInstanceOf('SclZfCartSagepay\Data\DataProvider', $cipher);
    }
}
