<?php
namespace SclZfCartSagepay\Service;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-15 at 17:30:38.
 */
class SagepayFactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var SagepayFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SagepayFactory;
    }

    /**
     * @covers SclZfCartSagepay\Service\SagepayFactory::createService
     * @todo   Implement testCreateService().
     */
    public function testCreateService()
    {
        $serviceLocator = $this->getMock('Zend\ServiceManager\ServiceLocatorInterface');

        $dataProvider = $this->getMockBuilder('SclZfCartSagepay\Data\DataProvider')
            ->disableOriginalConstructor()
            ->getMock();

        $serviceLocator->expects($this->once())
            ->method('get')
            ->with($this->equalTo('SclZfCartSagepay\Data\DataProvider'))
            ->will($this->returnValue($dataProvider));

        $cipher = $this->object->createService($serviceLocator);

        $this->assertInstanceOf('SclZfCartSagepay\Sagepay', $cipher);
    }
}
